//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO_Koleso
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cars()
        {
            this.serviceRequests = new HashSet<serviceRequests>();
        }
    
        public int carId { get; set; }
        public string mark { get; set; }
        public string model { get; set; }
        public int year { get; set; }
        public string color { get; set; }
        public int clientId { get; set; }
        public string FullInfo
        {
            get
            {
                return $"{mark} {model}, {year} г.";
            }
        }

        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceRequests> serviceRequests { get; set; }
    }
}
