//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO_Koleso
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartSerivce
    {
        public int cartId { get; set; }
        public int serviceId { get; set; }
        public int clientId { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual servicesList servicesList { get; set; }
    }
}
