//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO_Koleso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int markId { get; set; }
        public string markName { get; set; }
        public string image { get; set; }
    }
}
