//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO_Koleso
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceRequests
    {
        public int serviceRequestId { get; set; }
        public int serviceId { get; set; }
        public int clientId { get; set; }
        public int workerId { get; set; }
        public int carId { get; set; }
        public int statusId { get; set; }
        public System.DateTime dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string notes { get; set; }
    
        public virtual cars cars { get; set; }
        public virtual clients clients { get; set; }
        public virtual servicesList servicesList { get; set; }
        public virtual statusList statusList { get; set; }
        public virtual workers workers { get; set; }
    }
}
