//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STO_Koleso
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int userId { get; set; }
        public int roleId { get; set; }
        public int workerId { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual workers workers { get; set; }
    }
}
